title: Quant Flow Documentation
description: The comprehensive documentation for Quant Flow, Payscript and the Sandbox.
theme: just-the-docs

color_scheme: quant

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

favicon_ico: "/assets/images/favicon.ico"