title: Quant Flow Docs
description: The comprehensive documentation for Quant Flow, Payscript and the Sandbox.
theme: just-the-docs

color_scheme: quant

url: https://just-the-docs.github.io

aux_links:
  Quant: https://quant.network/
  Flow: https://quant.network/quant-flow/


favicon_ico: "/assets/images/favicon.ico"